name: Checks
on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup node v15
        uses: actions/setup-node@v3
        with:
          node-version: '15'
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines --frozen-lockfile
      - name: Run tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
